-- latest update: Mon Aug 31 04:34:29 2020
return {
	-- ["ModTemplate"] = {tags = {"demo"}, authors = {"TIS"}},
	["onedayfix41"] = {tags = {"Bugfix", "Tweak"}, authors = {"star"}},
	["TheNutritionist"] = {authors = {"RH4DB4"}},
	["SandboxPlus"] = {tags = {"Tweak", "Realistic"}, authors = {"derLoko"}},
	["svgMCerdato"] = {authors = {"erdato"}},
	["GoDzMoDsPack"] = {authors = {"Ricky", "eris"}},
	["AutoRepeatForage"] = {authors = {"RH4DB4"}},
	["VariedZombies"] = {authors = {"ddraigcymraeg"}},
	["ArmoredVests"] = {authors = {"Memmorath"}},
	["lighterAmmos"] = {authors = {"SepuLtera"}},
	["AdditionalBooks2"] = {tags = {"Items", "Literature"}, authors = {"Archi9"}},
	["ctm"] = {authors = {"Cleave"}},
	["Otr"] = {authors = {"Woldren"}},
	["BBushGreatCarsPack"] = {authors = {"blenderbush"}},
	["USFpack"] = {authors = {"W1 RALMAZ"}},
	["AzaRadio"] = {authors = {"Erin Azakaela Redfire"}},
	["RPGarbageDisposal"] = {authors = {"Pydgin", "Robob27"}},
	["SGuns"] = {tags = {"Textures", "Models", "Items", "Weapons", "Bugfix", "Realistic"}, authors = {"djvirus", "MayRum"}},
	["improvedmaps"] = {authors = {"Vaileasys"}},
	["westpointstripcenter"] = {authors = {"Rodajita"}},
	["SKLDairyModBeta"] = {authors = {"sugarskull"}},
	["LitSortOGSN_gold"] = {tags = {"Interface", "Items", "Literature", "Tweak", "Framework", "Language", "Realistic"}, authors = {"Oh God Spiders No"}},
	["LitSortOGSN_diamond"] = {tags = {"Interface", "Items", "Literature", "Tweak", "Framework", "Language", "Realistic"}, authors = {"Oh God Spiders No"}},
	["LitSortOGSN_readOnePage"] = {tags = {"Interface", "Items", "Literature", "Tweak", "Framework", "Language", "Realistic"}, authors = {"Oh God Spiders No"}},
	["LitSortOGSN"] = {tags = {"Interface", "Items", "Literature", "Tweak", "Framework", "Language", "Realistic"}, authors = {"Oh God Spiders No"}},
	["LitSortOGSN_chocolate"] = {tags = {"Interface", "Items", "Literature", "Tweak", "Framework", "Language", "Realistic"}, authors = {"Oh God Spiders No"}},
	["LitSortOGSN_rice"] = {tags = {"Interface", "Items", "Literature", "Tweak", "Framework", "Language", "Realistic"}, authors = {"Oh God Spiders No"}},
	["HECUGrunt"] = {tags = {"Textures", "Models", "Items", "Clothing", "Weapons", "Traits", "Framework", "Realistic"}, authors = {"Dr. Bright"}},
	["ManySpawns"] = {authors = {"Pillow"}},
	["ManySpawnsLocation"] = {authors = {"Pillow"}},
	["ManySpawnsProfession"] = {authors = {"Pillow"}},
	["ManySpawnsVariations"] = {authors = {"Pillow"}},
	["CLH_HobotText"] = {authors = {"star", "Lord Hobotok", "trublueberry"}},
	["PipeWrench"] = {authors = {"planetalgol"}},
	["amhghk2"] = {authors = {"ddraigcymraeg"}},
	["cheatmenuaiz"] = {authors = {"ddraigcymraeg"}},
	["Hydrocraft"] = {authors = {"David Hasihoff"}},
	["NocturnalZombies"] = {authors = {"nolanritchie"}},
	["HatRetexturePack"] = {authors = {"ROTFLOL"}},
	["Eerie Country"] = {authors = {"Otomie Warrior", "AtoxWarrior"}},
	["sizelabels41"] = {tags = {"Clothing", "Tweak", "Realistic"}, authors = {"star", "DobryaK"}},
	["OptimizeConsolidationTime"] = {authors = {"RH4DB4"}},
	["SovietAfghanWarSongPlaylist"] = {authors = {"Sturmovik"}},
	["curevirus"] = {authors = {"star"}},
	["SuperbSurvivors"] = {authors = {"nolanritchie"}},
	["Daegu"] = {authors = {"leejjangdol"}},
	["concussion_grenades"] = {authors = {"planetalgol"}},
	["Lore-friendly Custom Music"] = {authors = {"Beastlymeat"}},
	["ModTemplate"] = {authors = {"Ollie"}},
	["curevirus41"] = {authors = {"star"}},
	["pruningshears"] = {authors = {"WombatCombat"}},
	["inSayneElectrics"] = {authors = {"MisterInSayne"}},
	["policia"] = {authors = {"Todd Toddington"}},
	["eris_nightvision_goggles"] = {authors = {"eris"}},
	["VehicleSalvage"] = {authors = {"Jakor"}},
	["BookOfTheDead"] = {authors = {"Erin Azakaela Redfire"}},
	["VFFogsn"] = {tags = {"Food", "Bugfix", "Tweak"}, authors = {"Oh God Spiders No"}},
	["VFFogsn_herbsNoRot"] = {tags = {"Food", "Bugfix", "Tweak"}, authors = {"Oh God Spiders No"}},
	["NoDarkColors"] = {authors = {"star"}},
	["POS"] = {authors = {"EnigmaGrey"}},
	["M9Black"] = {authors = {"ROTFLOL"}},
	["M9Default"] = {authors = {"ROTFLOL"}},
	["M9Replacement"] = {authors = {"ROTFLOL"}},
	["M9Sand"] = {authors = {"ROTFLOL"}},
	["M9Stainless"] = {authors = {"ROTFLOL"}},
	["M9TwoTone"] = {authors = {"ROTFLOL"}},
	["ZombieLootExtended"] = {authors = {"Lars E. Paine"}},
	["crossbow_patch"] = {authors = {"planetalgol"}},
	["padlock_built_doors"] = {authors = {"planetalgol"}},
	["GimmeScrap"] = {authors = {"bibop"}},
	["ChineseGonganUsedSkin"] = {authors = {"HansKaffee"}},
	["DisplayRoughlyBedQuality"] = {tags = {"Interface"}, authors = {"RH4DB4"}},
	["2205858043"] = {tags = {"Items", "Food", "Realistic"}, authors = {"Alec"}},
	["fastkeys41"] = {tags = {"Tweak"}, authors = {"star"}},
	["MoreOriginalRecipes"] = {authors = {"JPF"}},
	["its3ampleasehelpme"] = {authors = {"Todd Toddington"}},
	["QuitSmoking"] = {authors = {"Pillow"}},
	["guncleaning"] = {authors = {"planetalgol"}},
	["Bigger Journals and Notepads"] = {authors = {"Erin Azakaela Redfire"}},
	["QG"] = {authors = {"Abdhaq"}},
	["SaveCustomiseCharacter"] = {authors = {"RH4DB4"}},
	["InfiniteWeather_OGSN_rain"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["InfiniteWeather_OGSN_snow"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["InfiniteWeather_OGSN_fog"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["SurgicalMask White (Green)"] = {tags = {"Textures", "Clothing", "Medical"}, authors = {"Bboy_Corentin"}},
	["LootZeta"] = {authors = {"Snake"}},
	["LetMeThink"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["CLH_RegionalMap"] = {authors = {"Lord Hobotok"}},
	["MysteryMachineOGSN"] = {tags = {"Textures", "Vehicles"}, authors = {"Oh God Spiders No"}},
	["CLH_MoreTraitsLangPlugin1803878992"] = {authors = {"Lord Hobotok"}},
	["GravityFix"] = {authors = {"planetalgol"}},
	["HealthBars"] = {tags = {"Interface"}, authors = {"RH4DB4"}},
	["ZSmokerLittering"] = {tags = {"Items", "Medical", "Tweak"}, authors = {"Madman_Andre (R.I.P. Rick May)"}},
	["WestPointExpansion"] = {authors = {"ww2commander"}},
	["VibrantColorPaletteOGSN"] = {tags = {"Interface", "Textures", "Clothing", "Tweak"}, authors = {"Oh God Spiders No"}},
	["1904952813"] = {tags = {"Textures", "Items", "Weapons", "Realistic"}, authors = {"Alec"}},
	["noitems"] = {tags = {"Clothing", "Tweak", "Harder"}, authors = {"star"}},
	["improvedbuildmenu41"] = {authors = {"Vaileasys"}},
	["MakeOnePageReadable"] = {authors = {"RH4DB4"}},
	["SuperSurvivors"] = {authors = {"nolanritchie"}},
	["GunNutTrait"] = {authors = {"darthboer"}},
	["Coordinate"] = {authors = {"ProjectSky"}},
	["UnbreakableMetalWalls"] = {authors = {"star"}},
	["alwaysfavorite"] = {tags = {"Interface", "Tweak"}, authors = {"star"}},
	["LockpickingOnly"] = {tags = {"Interface", "Items", "Traits", "Bugfix", "Easier", "Realistic"}, authors = {"Oh God Spiders No"}},
	["greenfirepatch"] = {authors = {"planetalgol"}},
	["Louisiana"] = {authors = {"TheCautiousOne"}},
	["AAApoc"] = {tags = {"Items", "Food"}, authors = {"Madman_Andre (R.I.P. Rick May)"}},
	["Creepy Critters"] = {authors = {"planetalgol"}},
	["1537876121"] = {tags = {"Items", "Food", "Realistic"}, authors = {"Alec", "Cleave", "Admiral.Slowpoke", "Twitch_Kovi16"}},
	["PillowsRandomScenarios"] = {authors = {"Pillow"}},
	["MANYBAGS"] = {authors = {"Dezert"}},
	["cherbourg"] = {authors = {"Lord Hobotok", "Kukrapok"}},
	["MandelaBowAndArrow"] = {authors = {"Gluten the Sensitive"}},
	["POSZONES"] = {tags = {"Multiplayer", "Interface"}, authors = {"star"}},
	["OGSN_orphan_AmmoMagazines"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["OGSN_Orphan_OrganizedStorage"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["OGSN_orphan_GoodTeaCoffeeVitamins"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["ForkMJdairy"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["ForkMJjarMeat"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["ForkMJsuperGarlic"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["ForkMJfoodWild"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["ForkMJtraits"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["OGSN_Orphan_RodsStore"] = {tags = {"Items", "Food", "Medical", "Traits", "Tweak"}, authors = {"Oh God Spiders No"}},
	["reallyrealtime"] = {tags = {"Multiplayer", "Tweak"}, authors = {"star"}},
	["harder_hotwire_nerf"] = {authors = {"Jason Taylor (Cirenmatt)"}},
	["Eyepatch"] = {authors = {"Ravenim"}},
	["CrashedCarsMod"] = {authors = {"JellySnek"}},
	["VehiclePartsRepair"] = {authors = {"Pure Fox"}},
	["300PointsTrait"] = {authors = {"Peu"}},
	["Swatpack"] = {authors = {"Relihschneider"}},
	["NYPDStuff"] = {authors = {"ArtyomRex01"}},
	["ModTemplate"] = {authors = {"Luminia"}},
	["HeroicWeaponsWSEDITING5/16"] = {authors = {"tommysticks"}},
	["NecroForge"] = {authors = {"ZedHead", "Svarog"}},
	["NecroForgePlugs"] = {authors = {"ZedHead", "Svarog"}},
	["FashionMontage"] = {tags = {"Interface", "Clothing", "Framework", "Realistic"}, authors = {"Oh God Spiders No"}},
	["showzedhealth"] = {authors = {"planetalgol"}},
	["NH"] = {authors = {"Monk"}},
	["GrabToCurrentInventory"] = {authors = {"RH4DB4"}},
	["YURcarts"] = {authors = {"Lily Cat"}},
	["WWI"] = {authors = {"Wilhelm IX"}},
	["WalkToExactly"] = {authors = {"RH4DB4"}},
	["ATP"] = {authors = {"nolanritchie"}},
	["Brita"] = {authors = {"BRITA"}},
	["NocturnalZombiesFixed"] = {authors = {"star"}},
	["2207313208"] = {tags = {"Items", "Food", "Realistic"}, authors = {"Alec", "Admiral.Slowpoke"}},
	["CryogenicWinter"] = {authors = {"pathmada"}},
	["CLH_RealCars"] = {authors = {"Lord Hobotok"}},
	["PickUpExceedCapacityItem"] = {authors = {"RH4DB4"}},
	["vehicle_additions"] = {authors = {"planetalgol"}},
	["spraypaint"] = {authors = {"Thuztor", "blindcoder"}},
	["PumpPower2"] = {authors = {"ddraigcymraeg"}},
	["ScrapWeapons"] = {tags = {"Textures", "Models", "Items", "Weapons", "Bugfix", "Realistic"}, authors = {"djvirus", "MayRum"}},
	["ToadTraits"] = {authors = {"Dilanyan"}},
	["cannedfix1"] = {authors = {"star"}},
	["ChainsawRevolution1"] = {authors = {"star"}},
	["Katana1"] = {authors = {"star"}},
	["lockpickingmod1"] = {authors = {"star"}},
	["Silencer1"] = {authors = {"star"}},
	["SKLDairyMod1"] = {authors = {"star"}},
	["Soap"] = {authors = {"ThatGuyRandom (TGR)"}},
	["PostApocalypticSprites"] = {authors = {"MarcOwaR"}},
	["zombiesdontburn"] = {authors = {"planetalgol"}},
	["BlackBag"] = {authors = {"ROTFLOL"}},
	["disablewelcome"] = {tags = {"Interface"}, authors = {"star"}},
	["modoptions"] = {tags = {"Interface", "Framework"}, authors = {"star"}},
	["CLH_Russian_Retexture"] = {authors = {"Lord Hobotok"}},
	["BlackBag"] = {authors = {"ROTFLOL"}},
	["RadialMenuEx"] = {tags = {"Interface", "Textures", "Bugfix"}, authors = {"star", "Lord Hobotok"}},
	["SpiffomonB41"] = {tags = {"Items"}, authors = {"Madman_Andre (R.I.P. Rick May)"}},
	["UAZ469"] = {authors = {"Lord Hobotok", "MrDanny"}},
	["CLH_HobotText41"] = {authors = {"star", "Lord Hobotok", "trublueberry", "Narrnika"}},
	["DisplayEquippedLocation"] = {authors = {"RH4DB4"}},
	["Mort"] = {authors = {"Erin Azakaela Redfire"}},
	["Waistbags"] = {authors = {"CynicRus"}},
	["PZGate"] = {authors = {"nolanritchie"}},
	["ORGMSilencer"] = {authors = {"nolanritchie"}},
	["FRUsedCarsBETA"] = {authors = {"Filibuster Rhymes"}},
	["OZMeds"] = {authors = {"darkkreepe"}},
	["CraftHelper41"] = {tags = {"Interface"}, authors = {"b1n0m"}},
	["Gunman6ptTrait"] = {authors = {"mattb224"}},
	["PropaneTankTweak"] = {authors = {"star"}},
	["nutritionindicator41"] = {tags = {"Interface"}, authors = {"star"}},
	["nosheetropesfromwindows40"] = {authors = {"planetalgol"}},
	["nosheetropesfromwindows41"] = {authors = {"planetalgol"}},
	["KeepAUTOSoundVolumes"] = {authors = {"RH4DB4"}},
	["EnhancedVehicles"] = {authors = {"PriMan", "varywolf", "Sintetik", "Di Crash"}},
	["eris_minimap"] = {authors = {"eris"}},
	["WW2Veteran"] = {tags = {"Models", "Items", "Weapons", "Traits", "Realistic", "Skills", "Military", "Roleplay"}, authors = {"Dr. Bright"}},
	["ALICE"] = {authors = {"Anonymous Prime", "Marcsoup", "begginfokillz"}},
	["hotbar"] = {authors = {"blindcoder"}},
	["cremation"] = {authors = {"Mose"}},
	["BedfordFalls"] = {authors = {"ringod123"}},
	["QS"] = {authors = {"Abdhaq"}},
	["Minecraft Bag"] = {authors = {"Ollie"}},
	["Better Belts"] = {authors = {"MayRum", "djvirus"}},
	["SuperbSurvivorz"] = {authors = {"RH4DB4"}},
	["RepairAnyClothes"] = {authors = {"Johnny Dollar"}},
	["Marijuanav2"] = {authors = {"Kilyin"}},
	["Raven Creek"] = {authors = {"DavidBlane"}},
	["CraftHelper"] = {authors = {"ddraigcymraeg"}},
	["FRSmallerCars"] = {authors = {"Filibuster Rhymes"}},
	["ReasonableHouseAlarm"] = {authors = {"RH4DB4"}},
	["KnoxCountryMap_OGSN"] = {tags = {"Interface", "Items", "Bugfix", "Tweak", "Realistic"}, authors = {"Oh God Spiders No"}},
	["M16"] = {authors = {"Alfcega"}},
	["HBVW_names"] = {authors = {"harrycheez"}},
	["HBVW"] = {authors = {"harrycheez"}},
	["antiserum"] = {authors = {"b1n0m"}},
	["SmartOpenMechanicsUI"] = {authors = {"RH4DB4"}},
	["SRCD"] = {tags = {"Items"}, authors = {"derLoko", "Admiral.Slowpoke"}},
	["traitsrebalance"] = {tags = {"Traits", "Tweak"}, authors = {"star"}},
	["ZedHealth"] = {authors = {"tommysticks"}},
	["sChineseTR"] = {authors = {"ProjectSky"}},
	["tnt-naturalclock"] = {authors = {"Thuztor"}},
	["GEARBASIC"] = {authors = {"planetalgol"}},
	["GEARCORE"] = {authors = {"planetalgol"}},
	["PfM"] = {authors = {"Purple Mab"}},
	["HairStyle"] = {authors = {"tommysticks"}},
	["GUNZ"] = {authors = {"[SIEGE] Kot"}},
	["873020165"] = {tags = {"Items", "Food", "Realistic"}, authors = {"Alec", "Cleave", "Admiral.Slowpoke", "Twitch_Kovi16", "Madman_Andre (R.I.P. Rick May)"}},
	["AuthenticSuicide"] = {authors = {"Ravenim"}},
	["PrisonShank"] = {authors = {"Flesh Forge"}},
	["BookCollection"] = {authors = {"Mecha", "Hryst"}},
	["GPS"] = {authors = {"Nemesis"}},
	["ReducedPlank"] = {authors = {"Human Male"}},
	["DriveCars"] = {authors = {"nolanritchie"}},
	["Xonics Mega Mall"] = {authors = {"Xonic"}},
	["NYPDUsedCarSkins"] = {authors = {"ArtyomRex01"}},
	["ToadTraits"] = {authors = {"HypnoToadTrance"}},
	["SurgicalMask White (Blue)"] = {tags = {"Textures", "Clothing", "Medical"}, authors = {"Bboy_Corentin"}},
	["MoreTrash"] = {authors = {"planetalgol"}},
	["SYNFreeSpawn"] = {authors = {"shuiyinv"}},
	["EscapeScavengeUI"] = {authors = {"RH4DB4"}},
	["Odintsovo"] = {authors = {"borisworm"}},
	["1993FurryConvention"] = {authors = {"Authentic Peach"}},
	["WSG"] = {authors = {"Woldren"}},
	["Survivors"] = {authors = {"ddraigcymraeg", "nolanritchie"}},
	["SRGMoreHairColours"] = {authors = {"sixstepsaway"}},
	["moretags41"] = {tags = {"Bugfix", "Tweak"}, authors = {"star"}},
	["LetMeThink38"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["LetMeThink39"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["LetMeThink40"] = {tags = {"Interface", "Tweak"}, authors = {"Oh God Spiders No"}},
	["DubsProfessionMod"] = {authors = {"Dubpub"}},
	["FasterReading++"] = {authors = {"Zero Bellum"}},
	["ArmorMod"] = {authors = {"nolanritchie"}},
	["ShowDMG"] = {authors = {"nolanritchie"}},
	["sortinginventory"] = {tags = {"Interface"}, authors = {"star"}},
	["Silencer"] = {authors = {"nolanritchie"}},
	["overlay_mod"] = {authors = {"ZedHead", "Viceroy"}},
	["CannedFix"] = {authors = {"istepan"}},
	["SimpleAddInventoryPages20191226"] = {authors = {"RH4DB4"}},
	["ArmorMod_build41_patch"] = {authors = {"planetalgol"}},
	["bcUtils"] = {authors = {"blindcoder"}},
	["Fort Knox"] = {authors = {"Woldren"}},
	["RussianTranslation"] = {authors = {"LeoIvanov"}},
	["QuickSwag"] = {authors = {"Abdhaq"}},
	["MWM"] = {authors = {"Polynudj", "FinchEz", "all my negative are thoughts"}},
	["Newgasmasktexture"] = {authors = {"pedor mrachny"}},
	["546189296"] = {authors = {"Onkeen"}},
	["USMilitaryPack"] = {authors = {"[CRG] Wayne"}},
	["SlocanLake"] = {authors = {"XeonyX"}},
	["South Muldraugh"] = {authors = {"Firechaser"}},
	["ttrKatanaFix"] = {authors = {"ttr"}},
	["CraftableAxes"] = {authors = {"istepan"}},
	["DixieSpawns"] = {authors = {"Pillow"}},
	["MoreBuild"] = {authors = {"ProjectSky"}},
	["Mcdonalds"] = {authors = {"Neutz"}},
	["Metal Baseball Bat [Rework]"] = {tags = {"Textures", "Weapons"}, authors = {"Bboy_Corentin"}},
	["ARIKORPATCH"] = {authors = {"Arioch"}},
	["Rebuild"] = {authors = {"Jela331"}},
	["cheatmenu"] = {authors = {"ethanwdp"}},
	["real_durabilities"] = {authors = {"Hisu"}},
	["HuntingMod"] = {authors = {"ungratefuldead88"}},
	["HomemadeGunpowder"] = {authors = {"Johnny Dollar"}},
	["2206552815"] = {tags = {"Items", "Weapons", "Realistic"}, authors = {"Alec"}},
	["1521582441"] = {tags = {"Items", "Food", "Realistic"}, authors = {"Alec", "Cleave", "Admiral.Slowpoke", "Twitch_Kovi16", "Madman_Andre (R.I.P. Rick May)"}},
	["Lighthousematrioshka"] = {authors = {"Matrioshka"}},
	["1557287920"] = {tags = {"Items"}, authors = {"Alec", "Admiral.Slowpoke"}},
	["SVGLittering"] = {authors = {"Svarog"}},
	["SVGLitteringME"] = {authors = {"Svarog"}},
	["Katana"] = {authors = {"Nemesis"}},
	["ItemTweakerAPI"] = {authors = {"DarkSlayerEX"}},
	["PZGatewayCustomProfession2"] = {authors = {"Harperers"}},
	["SVGHairColor"] = {authors = {"Svarog"}},
	["B41 Nail Gun"] = {tags = {"Models", "Weapons", "Easier"}, authors = {"djvirus"}},
	["NewGasStationMatrioshka"] = {authors = {"Matrioshka"}},
	["ExerciseFIX"] = {authors = {"self destruction"}},
	["MissingWeaponTextures"] = {authors = {"ROTFLOL"}},
	["MinimalDisplayBars"] = {tags = {"Multiplayer", "Interface"}, authors = {"ATPHHe"}},
	["iCDPlayersSV"] = {authors = {"Nebula"}},
	["AxesRecrafting"] = {authors = {"Shokin"}},
	["CLH_RUVanillaCars"] = {authors = {"Lord Hobotok"}},
	["BanjoStartDixiePark"] = {authors = {"Banjo Oz"}},
	["UAZ452Police"] = {authors = {"Lord Hobotok", "MrDanny"}},
	["ZedHealthNew"] = {authors = {"pauldeelaek"}},
	["Toothpaste"] = {tags = {"Items", "Medical", "Realistic"}, authors = {"Madman_Andre (R.I.P. Rick May)"}},
	["Multitool"] = {authors = {"planetalgol"}},
	["Multitool Hydrocraft Patch"] = {authors = {"planetalgol"}},
	["Multitool Scrap Guns Patch"] = {authors = {"planetalgol"}},
	["Multitool Scrap Weapon Patch"] = {authors = {"planetalgol"}},
	["MREMeal"] = {authors = {"Blackbeard"}},
	["Re2CT"] = {authors = {"Pr1vateLime"}},
	["The Walking Dead Project-Pack"] = {authors = {"Woldren", "aeneasromae"}},
	["AuthenticAnimations"] = {authors = {"Ravenim", "Authentic Peach", "Erin Azakaela Redfire"}},
	["2116762736"] = {authors = {"Befurit"}},
	["SvgBookMod"] = {authors = {"Svarog"}},
	["MPZombieLoot"] = {authors = {"* DTMAG * - Kloburste aka SomiX"}},
	["DigitalWatchTimer"] = {authors = {"Pandafish"}},
	["PornoMags"] = {authors = {"planetalgol"}},
	["DeLoreanDMC-12"] = {tags = {"Vehicles"}, authors = {"MrDanny"}},
	["TKCM"] = {authors = {"Luchettinni"}},
	["UncleSharksKentuckyCarnage"] = {authors = {"shark"}},
	["VSTOWN"] = {authors = {"EnvyDemon"}},
	["NUK"] = {authors = {"Blackbeard"}},
	["IWDR"] = {authors = {"star", "Artoria"}},
	["RadioExperienceFix"] = {tags = {"Bugfix", "Tweak"}, authors = {"Oh God Spiders No"}},
	["ReadFasterWhenSitting"] = {authors = {"RH4DB4"}},
	["LootZeta41"] = {authors = {"Snake"}},
	["RepairAnySWAT"] = {authors = {"Johnny Dollar"}},
	["ADVANCEDGEAR"] = {authors = {"planetalgol"}},
	["FORTREDSTONE"] = {authors = {"Neutz"}},
	["ZAZ968M"] = {tags = {"Vehicles"}, authors = {"MrDanny"}},
	["MREMeal41"] = {authors = {"Blackbeard"}},
	["marchingpowder"] = {authors = {"planetalgol"}},
	["realisticinventory"] = {tags = {"Items", "Tweak", "Harder", "Realistic"}, authors = {"star", "Astro"}},
	["WestPointExpansionAddonLootMap"] = {authors = {"ww2commander"}},
	["DroppableEvenIfMoving"] = {authors = {"RH4DB4"}},
	["Dreams"] = {authors = {"Nebula", "star"}},
	["CCCP"] = {tags = {"Items", "Food"}, authors = {"Madman_Andre (R.I.P. Rick May)"}},
	["windowseverywhere"] = {tags = {"Interface", "Tweak"}, authors = {"star"}},
	["FirearmEnthusiastTrait"] = {authors = {"Sowilo"}},
	["showmaterial"] = {tags = {"Interface"}, authors = {"star"}},
	["MinecraftDiamondPickaxe"] = {authors = {"ROTFLOL"}},
	["TheCrows"] = {authors = {"Erin Azakaela Redfire"}},
	["VileM113APC"] = {authors = {"Vilespring"}},
	["FearTheSun"] = {authors = {"Pillow"}},
	["SeriousSurviviors"] = {authors = {"planetalgol"}},
	["ToSBackpacks Build41"] = {authors = {"Alfcega"}},
	["cuttingarea"] = {authors = {"ShtopoR"}},
	["TieOnSpearheads"] = {tags = {"Weapons", "Tweak", "Realistic"}, authors = {"Oh God Spiders No"}},
	["TieOnSpearheads_MP"] = {tags = {"Weapons", "Tweak", "Realistic"}, authors = {"Oh God Spiders No"}},
	["RedCrowbarRetexture"] = {authors = {"ROTFLOL"}},
	["tailoringfix41"] = {tags = {"Clothing", "Bugfix", "Tweak"}, authors = {"star"}},
	["ORGM"] = {authors = {"CR25DireBookworm", "Khaos", "Fenris_Wolf"}},
	["serVarTranslationRusHydrocraft"] = {authors = {"Var"}},
	["CraftSoap"] = {authors = {"MrRAT"}},
	["FRUsedCars"] = {authors = {"Filibuster Rhymes"}},
	["SecretBaseRoad"] = {authors = {"Madman_Andre (R.I.P. Rick May)"}},
	["NolansTrapsUpdates"] = {authors = {"planetalgol"}},
	["KCMcrossbow"] = {authors = {"Kitsune"}},
	["NodachiMod"] = {authors = {"SmokeAnDrink"}},
	["Exercise"] = {authors = {"Jambuster"}},
	["SuperNintendo"] = {authors = {"Erin Azakaela Redfire"}},
	["harder_hotwire"] = {tags = {"Multiplayer", "Interface", "Vehicles", "Harder"}, authors = {"rez", "outdead"}},
	["CorpseStudy"] = {authors = {"mattb224"}},
	["RPQuickSort"] = {authors = {"Robob27", "Pydgin"}},
	["Hydrocraft"] = {authors = {"Hydromancerx", "DemolitionDerby"}},
	["Threads"] = {authors = {"Johnny Dollar"}},
	["AUpack"] = {authors = {"FatBee"}},
	["CabinsSpawn"] = {authors = {"Pillow"}},
	["BetterClothing"] = {authors = {"Niko241"}},
	["TheLastCity by Woldren"] = {authors = {"Woldren"}},
	["BookHelper"] = {tags = {"Interface", "Literature"}, authors = {"b1n0m"}},
	["Mod_Phoenix"] = {authors = {"MonolithicBacon"}},
	["ExpirationFoodR"] = {authors = {"rez"}},
	["HCORGM"] = {authors = {"Atlas1205"}},
	["UAZ452PACK"] = {authors = {"Lord Hobotok", "MrDanny"}},
	["OpenCanWithKnife"] = {authors = {"enigma spamer"}},
	["ReadingIsNotBoring"] = {authors = {"RH4DB4"}},
	["ttrKatanaRemake"] = {authors = {"ttr"}},
	["UNIQUEZ"] = {authors = {"Neutz"}},
	["UnSterilizeRags"] = {tags = {"Tweak", "Realistic"}, authors = {"Oh God Spiders No"}},
	["toxicfog"] = {authors = {"planetalgol"}},
	["toxicfogandrain"] = {authors = {"planetalgol"}},
	["PLLoot"] = {authors = {"Kit Ty"}},
	["PLLootF"] = {authors = {"Kit Ty"}},
}
